name: Despliegue a GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Encapsular el código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          pip install flet

      - name: Construir la distribución
        run: |
          flet publish src/main.py --base-url /ekmajstro-malabunda-frontend/ --pwa-background-color "#1F1D2A" --app-name "Ekmajstro Malabunda" --app-short-name "Malabunda" --app-description "(Ekmajstro) Malabunda es un sistema para la gestión de entes políticos con el objetivo de permitir la visualización de un grafo de oligarquía, así como la consulta de datos tipo bitácora de cada ente político y su respectivo cálculo del grado de oligarquía." --pwa-theme-color "#1F1D2A"

      - name: Forzar estilo de la página
        run: |
          sed -i 's/<body>/<body style="background-color: #1F1D2A;">/g' src/dist/index.html
      
      - name: Agregar archivo 404.html
        run: cp src/dist/index.html src/dist/404.html

      - name: Desplegar a GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: src/dist
          branch: gh-pages